name: Validate with hassfest

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron:  '13 3 * * *'

jobs:
  validate:
    runs-on: ubuntu-latest
    name: hassfest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Test hassfest
        uses: home-assistant/actions/hassfest@master
